import React from "react";
import { useTranslation } from "react-i18next";
import { COLORS } from "../utils/constants";
import { SUPPORTED_MARKETS } from "../utils/localization";

export default function InternationalPage() {
  const { t } = useTranslation();
  const launchPlan = t("internationalPage.launchPlan", { returnObjects: true });
  const markets = Object.entries(SUPPORTED_MARKETS);
  const launchChecklist = t("internationalPage.checklist", { returnObjects: true });
  const crossBorderControls = t("internationalPage.crossBorder", { returnObjects: true });

  return (
    <main style={{ minHeight: "100vh", background: COLORS.bg }}>
      <section style={{ background: COLORS.white, padding: "5rem 2rem 3rem", borderBottom: `1px solid ${COLORS.border}` }}><div style={{ maxWidth: "1120px", margin: "0 auto" }}><p style={{ color: COLORS.gold, letterSpacing: "0.12em", textTransform: "uppercase", fontWeight: 900, marginBottom: "0.75rem" }}>{t("internationalPage.eyebrow")}</p><h1 style={{ color: COLORS.navy, fontSize: "clamp(2rem, 4vw, 3.4rem)", lineHeight: 1.1, marginBottom: "1rem" }}>{t("internationalPage.title")}</h1><p style={{ color: COLORS.textMuted, maxWidth: "780px", lineHeight: 1.7, fontSize: "1rem" }}>{t("internationalPage.description")}</p></div></section>
      <section style={{ padding: "3rem 2rem" }}><div style={{ maxWidth: "1120px", margin: "0 auto" }}><h2 style={{ color: COLORS.navy, fontSize: "1.6rem", marginBottom: "1rem" }}>{t("internationalPage.routeTitle")}</h2><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(260px, 1fr))", gap: "1rem" }}>{launchPlan.map((item) => <article key={item.phase} style={{ background: COLORS.white, border: `1px solid ${COLORS.border}`, borderRadius: "8px", padding: "1.4rem" }}><p style={{ color: COLORS.gold, fontSize: "0.75rem", fontWeight: 900, textTransform: "uppercase", marginBottom: "0.4rem" }}>{item.status}</p><h3 style={{ color: COLORS.navy, fontSize: "1.15rem", marginBottom: "0.35rem" }}>{item.phase}</h3><p style={{ color: COLORS.navy, fontWeight: 900, marginBottom: "0.6rem" }}>{item.markets}</p><p style={{ color: COLORS.textMuted, lineHeight: 1.6, fontSize: "0.9rem" }}>{item.scope}</p></article>)}</div></div></section>
      <section style={{ padding: "0 2rem 4rem" }}><div style={{ maxWidth: "1120px", margin: "0 auto" }}><h2 style={{ color: COLORS.navy, fontSize: "1.6rem", marginBottom: "1rem" }}>{t("internationalPage.marketsTitle")}</h2><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", gap: "1rem" }}>{markets.map(([code, market]) => <article key={code} style={{ background: COLORS.white, border: `1px solid ${COLORS.border}`, borderRadius: "8px", padding: "1.2rem" }}><p style={{ color: COLORS.gold, fontWeight: 900, fontSize: "0.75rem", marginBottom: "0.25rem" }}>{code}</p><h3 style={{ color: COLORS.navy, fontSize: "1rem", marginBottom: "0.35rem" }}>{market.label}</h3><p style={{ color: COLORS.textMuted, fontSize: "0.84rem", lineHeight: 1.5 }}>{market.locale} / {market.currency}</p><p style={{ color: COLORS.textMuted, fontSize: "0.78rem", lineHeight: 1.5, marginTop: "0.45rem" }}>{market.regulatorFocus.join(", ")}</p></article>)}</div></div></section>
      <section style={{ padding: "0 2rem 4rem" }}><div style={{ maxWidth: "1120px", margin: "0 auto", background: COLORS.white, border: `1px solid ${COLORS.border}`, borderRadius: "8px", padding: "1.5rem" }}><h2 style={{ color: COLORS.navy, fontSize: "1.5rem", marginBottom: "0.75rem" }}>{t("internationalPage.crossTitle")}</h2><p style={{ color: COLORS.textMuted, lineHeight: 1.6, maxWidth: "820px", marginBottom: "1.2rem" }}>{t("internationalPage.crossText")}</p><div style={{ display: "grid", gap: "0.75rem" }}>{crossBorderControls.map(([market, status, detail]) => <div key={market} style={{ display: "grid", gridTemplateColumns: "150px 170px 1fr", gap: "0.8rem", alignItems: "center", padding: "0.9rem", borderRadius: "8px", background: COLORS.bg, border: `1px solid ${COLORS.border}` }}><strong style={{ color: COLORS.navy }}>{market}</strong><span style={{ color: status.includes("No") || status.includes("Do not") ? "#C62828" : status.includes("Piloto") || status.includes("Pilot") ? COLORS.amber : COLORS.green, fontWeight: 900 }}>{status}</span><span style={{ color: COLORS.textMuted, fontSize: "0.84rem", lineHeight: 1.45 }}>{detail}</span></div>)}</div></div></section>
      <section style={{ padding: "0 2rem 5rem" }}><div style={{ maxWidth: "1120px", margin: "0 auto", background: COLORS.white, border: `1px solid ${COLORS.border}`, borderRadius: "8px", padding: "1.5rem" }}><h2 style={{ color: COLORS.navy, fontSize: "1.5rem", marginBottom: "0.75rem" }}>{t("internationalPage.checklistTitle")}</h2><p style={{ color: COLORS.textMuted, lineHeight: 1.6, maxWidth: "820px", marginBottom: "1.2rem" }}>{t("internationalPage.checklistText")}</p><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))", gap: "0.85rem" }}>{launchChecklist.map(([title, detail]) => <div key={title} style={{ background: COLORS.bg, border: `1px solid ${COLORS.border}`, borderRadius: "8px", padding: "1rem" }}><p style={{ color: COLORS.navy, fontWeight: 900, marginBottom: "0.35rem" }}>{title}</p><p style={{ color: COLORS.textMuted, fontSize: "0.84rem", lineHeight: 1.5 }}>{detail}</p></div>)}</div></div></section>
    </main>
  );
}
