from pathlib import Path
root=Path(__file__).resolve().parents[1]/'docs'/'nuxera-migration'/'docs'/'migration'
asset='./assets/qa-2026-07-29'
imgs={'public':f'![Public site]({asset}/public-home-en.png)','app':f'![Applicant]({asset}/applicant-dashboard-en.png)','grantor':f'![Funding provider]({asset}/grantor-workspace-en.png)','admin':f'![Admin]({asset}/admin-operations-en.png)'}
def b(items): return '\n'.join('- '+x for x in items)
def n(items): return '\n'.join(f'{i}. {x}' for i,x in enumerate(items,1))
def h(t,body): return f'\n## {t}\n\n{body}\n'
def sh(t,body): return f'\n### {t}\n\n{body}\n'
common_docs=['Acta constitutiva o registro equivalente','Poderes y representante legal','Identificacion de responsables y beneficiarios finales','Comprobante fiscal o numero tributario','Registro mercantil o licencia comercial','Estructura accionaria','Estados financieros','Modelo financiero','Presupuesto de inversion','Permisos y licencias','Contratos relevantes','Evidencia tecnica','Garantias','Informacion ESG o impacto']
source_list=['UAE PASS','EOCN','SCA/CMA','CBUAE','DFSA','FSRA/ADGM','ADGM Registration Authority','VARA','FTA','National Economic Registry','DET/DED Dubai','ADDED Abu Dhabi','registros economicos locales']
risks=['economico','politico','social','regulatorio','territorial','reputacional','documental','financiero','operativo','jurisdiccional']
def functional(lang='ES'):
 title='Manual Funcional Extendido' if lang=='ES' else 'Extended Functional Manual'
 out=[f'# NUXERA - {title}\n\nFecha/Date: 2026-07-29\nAudiencia/Audience: negocio, cumplimiento, usuarios operativos, socios e inversionistas.\n\nEste documento reemplaza el manual corto previo. Su objetivo es explicar NUXERA como plataforma operativa, no como resumen ejecutivo: que hace cada area, como entrar, que datos se capturan, como se cargan documentos, que revisa el otorgante, como actua administracion, que hacen agentes/notificaciones y que resultado produce cada ciclo.']
 out.append(h('1. Concepto general','NUXERA organiza expedientes de financiamiento con evidencia, cumplimiento, riesgo y revision humana. No aprueba credito automaticamente. La plataforma separa pagina publica, solicitantes, otorgantes y administracion para evitar que captura, analisis y control se mezclen. El resultado esperado es un expediente defendible, trazable y listo para comite humano.'))
 out.append(h('2. Principios de operacion',b(['La decision final siempre corresponde a humanos autorizados','Todo dato importante debe tener fuente, documento, usuario, fecha o evento','Los roles se separan por permisos y RLS','Los documentos sensibles no se adjuntan por correo por defecto','El agente solo usa contexto autorizado','Las fuentes externas muestran alcance y limitaciones','Demo e investor-ready no equivalen a produccion con datos reales'])))
 out.append(h('3. Pagina publica',imgs['public']+'\n\nLa pagina publica presenta NUXERA al mercado. No carga documentos sensibles ni genera score; explica propuesta de valor, cobertura global, industrias, integraciones e implementacion.\n\n'+sh('Como operar esta vista',n(['Abrir URL publica','Verificar marca NUXERA Financial Intelligence','Cambiar idioma ES/EN si aplica','Revisar Home, Platform, Global coverage, Industries, Integrations e Implementation','Entrar a Login o Sign Up solo cuando el usuario pasara a workspace']))))
 app=[imgs['app'],'El workspace de solicitantes prepara el expediente antes de compartirlo. Debe contestar que falta, que documentos subir, que riesgos estan abiertos y que sigue.',sh('Ingreso y primera lectura',n(['Iniciar sesion como solicitante','Abrir dashboard','Confirmar NUXERA / Applicant o Solicitante','Revisar readiness','Entrar a empresa, responsables, proyecto, documentos y seguimiento'])),sh('Empresa y responsables','Captura nombre legal, pais, registro, domicilio, sector, representante, beneficiarios finales y contactos. Documentos tipicos:\n\n'+b(common_docs[:7])+'\n\nNUXERA clasifica, marca faltantes, alimenta checklist y prepara senales para otorgante.'),sh('Proyecto y uso de fondos','Captura ubicacion pais/estado/ciudad, sector, monto, moneda, uso de fondos, etapa, plazo, garantias, modelo, impacto y permisos. Documentos tipicos:\n\n'+b(common_docs[7:])),sh('Carga documental paso a paso',n(['Seleccionar requisito o categoria','Subir archivo','Asociar a requisito','Confirmar version, fecha y responsable','Esperar estado recibido/en revision/observado/aprobado','Atender observacion o cargar nueva version'])+'\n\nCategorias: identidad, corporativo, fiscal, financiero, legal, tecnico, proyecto, garantias, cumplimiento, regulatorio, impacto y evidencia complementaria.'),sh('Score, seguimiento y agente','Readiness mide preparacion, no aprobacion. El agente puede explicar faltantes y requisitos, pero no promete condiciones, no aprueba financiamiento, no inventa datos y no muestra informacion de otros usuarios.')]
 out.append(h('4. Workspace de solicitantes','\n\n'.join(app)))
 gr=[imgs['grantor'],'El workspace de otorgantes transforma expedientes autorizados en analisis, comite y seguimiento. No debe duplicar la pantalla de solicitante.',sh('Decision desk','Prepara paquete de decision no vinculante: resumen, evidencia, riesgos, preguntas de comite, condiciones humanas, fuentes y limitaciones.'),sh('Case management','Mueve el caso: responsable, SLA, faltantes, solicitudes, expedientes detenidos e intervencion humana. Decision desk mira la decision; Case management mueve la operacion.'),sh('Finance e intelligence','Finance revisa monto, moneda, uso de fondos, repago, garantias, modelo y sensibilidad. Intelligence revisa empresa, representantes, beneficiarios, sanciones, reputacion, fuentes abiertas y hallazgos trazados.'),sh('Pais, ciudad y contexto','Debe analizar dimensiones '+', '.join(risks[:5])+'. El flujo es: ubicacion capturada por solicitante, fuente publica/API, separacion de datos confirmados y pendientes, resumen para otorgante con fecha, fuente, alcance y limitacion.'),sh('Medio Oriente y EAU','Fuentes consideradas:\n\n'+b(source_list)+'\n\nEn solicitante alimentan checklist y score sin saturar. En otorgante se muestran explicitamente con alcance, estatus, tipo de acceso, limitacion y siguiente accion.'),sh('Agente para otorgante','Puede resumir, preparar preguntas de comite, explicar faltantes, comparar evidencia, redactar solicitudes y memo no vinculante. No puede aprobar, emitir term sheet vinculante, ignorar faltantes, consultar sin permisos ni enviar correos sin gate.')]
 out.append(h('5. Workspace de otorgantes','\n\n'.join(gr)))
 ad=[imgs['admin'],'Admin controla usuarios, permisos, fuentes, agentes, notificaciones, seguridad, RLS, persistencia y cutover.',sh('Ingreso y modulos',n(['Iniciar sesion admin','Revisar Operations','Revisar Security/RLS','Revisar AI & agents','Revisar System/deploys/gates','Revisar fuentes regulatorias'])),sh('Usuarios y permisos',b(['Alta/baja de usuarios','Roles solicitante/otorgante/admin','Data rooms autorizados','Separacion demo vs produccion','Revision de accesos antes de compartir evidencia'])),sh('Catalogo de fuentes',b(['Nombre, pais, jurisdiccion y tipo de dato','Modo de acceso: publico, descarga, API, convenio o no disponible','Estatus live, condicional, privado, pendiente o bloqueado','Fecha de ultima revision y responsable','Limitaciones para no exagerar cobertura','Siguiente accion para integracion real'])),sh('Notificaciones','Eventos: bienvenida, expediente creado, documento faltante, documento recibido, observacion, aclaracion, estatus, nuevo expediente autorizado, evidencia nueva, SLA, revision humana, memo listo y riesgo critico. Fases: dry-run, sandbox, produccion limitada y produccion completa.'),sh('Agentes e IA','OpenAI y Anthropic son principales; Kimi bajo costo/bajo riesgo; DeepSeek detras de principales y bajo riesgo; NVIDIA experimental. Admin ve proveedor, tareas permitidas, riesgo maximo, logs, runtime y fallas.'),sh('Persistencia y cutover','Antes de produccion: eventos, aprobaciones, procedencia documental, RLS, tokens staging, logs y rollback. Cutover: inventario Nexus, QA, redireccion, monitoreo y plan de regreso.')]
 out.append(h('6. Administracion','\n\n'.join(ad)))
 out.append(h('7. Ciclo completo',n(['Solicitante crea expediente','Carga datos y documentos','NUXERA calcula readiness','Admin controla fuentes y gates','Otorgante accede si esta autorizado','Otorgante revisa evidencia y riesgos','Agente apoya bajo limites','Notificaciones mueven solicitudes','Persistencia registra eventos','Decision humana se documenta'])))
 return '\n'.join(out)
def technical(lang='ES'):
 title='Manual Tecnico Extendido' if lang=='ES' else 'Extended Technical Manual'; data=['usuarios','roles','expedientes','empresas','personas relacionadas','proyectos','documentos','requisitos','eventos','notificaciones','aprobaciones','fuentes regulatorias','agent_runs','jurisdiction_snapshots']; tables=['nuxera_case_events','nuxera_notification_approvals','nuxera_document_provenance','nuxera_regulatory_sources','nuxera_agent_runs','nuxera_jurisdiction_snapshots']
 return '\n'.join([f'# NUXERA - {title}\n\nFecha/Date: 2026-07-29\nAudiencia/Audience: equipo tecnico, CTO, integradores, DevOps, seguridad y due diligence tecnico.',h('1. Arquitectura',b(['React/Vite frontend','Node/Express backend','Supabase/SQL previsto','Vercel frontend','Render backend actual con latencia pendiente','Shell por roles','Servicios NUXERA protegidos','Automatizaciones por gates'])),h('2. Frontend',b(['Separacion por rol','ES/EN','Sin identidad Nexus visible','Vistas demo no prueban auth real','Decision desk distinto de case management','Admin como control operativo'])),h('3. Backend y servicios',b(['nuxeraJurisdictionIntelligenceService','nuxeraOperationalPersistenceService','nuxeraConversationAgentReadinessService','rutas readiness/evidencia/persistencia/admin','fallo cerrado sin token/rol/autorizacion'])),h('4. Modelo de datos',b(data)+'\n\nTablas sugeridas:\n\n'+b(tables)),h('5. RLS y seguridad',n(['Solicitante A no ve B','Otorgante no autorizado no ve expediente','Otorgante solo ve data room permitido','Admin requiere rol','Service role solo flujos controlados','Agente recibe contexto filtrado','Correo no expone documentos'])),h('6. Notificaciones','Componentes: eventos, plantillas, outbox, proveedor, approvals, reintentos y logs. Fases: dry-run, sandbox, produccion limitada y produccion completa.'),h('7. Agentes',b(['Context Manifest obligatorio','OpenAI/Anthropic principales','Kimi bajo riesgo','DeepSeek bajo riesgo detras de principales','NVIDIA experimental','Prohibido aprobar o emitir decision vinculante','Prohibido inventar evidencia o filtrar datos'])),h('8. Jurisdiccion','Analiza '+', '.join(risks)+'. Cada conclusion necesita fuente, fecha, alcance, limitacion, confianza y siguiente accion.'),h('9. Medio Oriente',b(source_list)),h('10. Deploy y cutover',n(['Congelar cambios','Ejecutar tests','Validar Vercel','Calentar backend','Validar RLS','Validar sandbox correo','Revisar URLs Nexus','Redirigir a NUXERA','Mantener rollback','Monitorear 24-48h'])),h('11. Pruebas recientes',b(['Backend 86/86','Frontend 125/125','Build Vite aprobado','QA visual 4/4','Vercel HTTP 200','Render timeout 20s pendiente']))])
def qa(lang='ES'):
 title='Manual Extendido de Pruebas y Evidencia' if lang=='ES' else 'Extended Testing and Evidence Manual'
 return '\n'.join([f'# NUXERA - {title}\n\nFecha/Date: 2026-07-29',h('1. Alcance',b(['QA visual','Backend tests','Frontend tests','Build','Smoke Vercel/Render','Ausencia visible Nexus'])),h('2. Pagina publica',imgs['public']+'\n\nValidado: carga, NUXERA visible, sin Nexus, lectura en ingles.'),h('3. Solicitante',imgs['app']+'\n\nValidado: dashboard applicant, readiness, preparacion, sin Nexus.'),h('4. Otorgante',imgs['grantor']+'\n\nValidado: funding provider, decision desk, case management, sin Nexus.'),h('5. Admin',imgs['admin']+'\n\nValidado: operations, modulos protegidos, rol admin, sin Nexus.'),h('6. Resultados',b(['Backend: 86/86','Frontend: 125/125','Build: aprobado','Visual: 4/4','Nexus visible: 0'])),h('7. Limitaciones',b(['localStorage demo','sin RLS real','sin usuarios reales','sin upload productivo','sin correo live','sin agente con datos reales','sin APIs privadas'])),h('8. Pendientes de QA',n(['RLS solicitante A/B','otorgante autorizado/no autorizado','admin con/sin rol','upload/versionado','sandbox correo','agente por rol','jurisdiccion pais-ciudad','SQL rehearsal','cutover rollback']))])
def remaining(lang='ES'):
 title='Plan Extendido de Pendientes Reales, Produccion y Cutover' if lang=='ES' else 'Extended Real Remaining Work, Production and Cutover Plan'
 return '\n'.join([f'# NUXERA - {title}\n\nFecha/Date: 2026-07-29',h('1. Estado',b(['90-92% demo/investor-ready','78-82% produccion real','Falta cerrar ciclos reales, no mas pantallas'])),h('2. Criticos',b(['RLS fase 2','SQL persistence rehearsal','correo sandbox','agente con contexto autorizado','backend estable','fuentes privadas por convenio','cutover Nexus->NUXERA','rollback'])),h('3. Plan de cutover',n(['Inventario de URLs','redirecciones','freeze','QA','demo final','backup rollback','cambio principal','monitoreo','correcciones','retiro remanentes'])),h('4. Riesgos',b(['backend frio','prometer fuentes privadas','correo sin sandbox','agente sin RLS','score confundido con aprobacion','tabs duplicadas'])),h('5. Recomendacion','Avanzar para inversionistas con demo controlada; no activar clientes reales hasta cerrar RLS, SQL, correo, agente seguro y cutover.')])
def en(text):
 repl={'Manual Funcional Extendido':'Extended Functional Manual','Manual Tecnico Extendido':'Extended Technical Manual','Manual Extendido de Pruebas y Evidencia':'Extended Testing and Evidence Manual','Plan Extendido de Pendientes Reales, Produccion y Cutover':'Extended Real Remaining Work, Production and Cutover Plan','solicitante':'applicant','Solicitante':'Applicant','otorgante':'funding provider','Otorgante':'Funding Provider','administrador':'administrator','Administrador':'Administrator','Pagina publica':'Public site','produccion':'production','documentos':'documents','expediente':'file','pruebas':'tests','aprobado':'passed'}
 for k,v in repl.items(): text=text.replace(k,v)
 return text
files={'NUXERA_MANUAL_FUNCIONAL_DETALLADO_2026-07-29_ES.md':functional('ES'),'NUXERA_DETAILED_FUNCTIONAL_MANUAL_2026-07-29_EN.md':en(functional('EN')),'NUXERA_MANUAL_TECNICO_DETALLADO_2026-07-29_ES.md':technical('ES'),'NUXERA_DETAILED_TECHNICAL_MANUAL_2026-07-29_EN.md':en(technical('EN')),'NUXERA_PRUEBAS_Y_EVIDENCIA_VISUAL_2026-07-29_ES.md':qa('ES'),'NUXERA_TESTING_AND_VISUAL_EVIDENCE_2026-07-29_EN.md':en(qa('EN')),'NUXERA_LO_QUE_FALTA_REALMENTE_2026-07-29_ES.md':remaining('ES'),'NUXERA_REAL_REMAINING_WORK_2026-07-29_EN.md':en(remaining('EN'))}
for name,text in files.items():
 (root/name).write_text(text,encoding='utf-8')
 print(name,len(text))
